language: cpp
sudo: required
dist: trusty
group: deprecated-2017Q4
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - clang
env: 
global:
   - CMAKE_VERSION="3.10.0"
   - CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
compiler:
  - gcc
  - clang
  
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo apt install llvm

before_script:
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - mkdir build
  - cd build
  - cmake ..
script:
  - pwd
  - make
