language: cpp
sudo: required
dist: trusty
group: deprecated-2017Q4
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - clang
env: 
global:
   - CMAKE_VERSION="3.9.1"
compiler:
  - gcc
  - clang
  
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo apt install llvm
  - sudo apt install cmake
script:
  - cmake .
  - make
